# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: ci-build-test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0

      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v2.2.0
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: build
        run: make binary

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0

      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v2.2.0
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: build
        run: make test
